name: network-based-application-recognization-nbar
mgmt:
  network: mgmt-ipv4
  ipv4-subnet: 10.65.97.0/24
topology:
  kinds:
    cisco_iol:
      image: docker-registry.nwl.lab/cisco_iol:17.12.01
  nodes:
    Drowsy:
      kind: cisco_iol
      mgmt-ipv4: 10.65.97.100
      startup-config: ./clab-network-based-application-recognization-nbar/Drowsy/startup-config.cfg.partial
    Sluggish:
      kind: cisco_iol
      mgmt-ipv4: 10.65.97.110
      startup-config: ./clab-network-based-application-recognization-nbar/Sluggish/startup-config.cfg.partial
    Lazy:
      kind: cisco_iol
      mgmt-ipv4: 10.65.97.120
      startup-config: ./clab-network-based-application-recognization-nbar/Lazy/startup-config.cfg.partial
  links:
  - endpoints:
    - Drowsy:Ethernet0/1
    - Sluggish:Ethernet0/2
  - endpoints:
    - Sluggish:Ethernet0/1
    - Lazy:Ethernet0/1
