name: ipv6-6rd-rapid-deployment
mgmt:
  network: statics
  ipv4-subnet: 172.100.100.0/24
topology:
  nodes:
    CE1:
      kind: cisco_iol
      mgmt-ipv4: 172.100.100.10
      startup-config: ./clab-ipv6-6rd-rapid-deployment/CE1/startup-config.cfg
    BR1:
      kind: cisco_iol
      mgmt-ipv4: 172.100.100.11
      startup-config: ./clab-ipv6-6rd-rapid-deployment/BR1/startup-config.cfg
    CE2:
      kind: cisco_iol
      mgmt-ipv4: 172.100.100.12
      startup-config: ./clab-ipv6-6rd-rapid-deployment/CE2/startup-config.cfg
    unmanagedswitch-1:
      kind: cisco_iol
      mgmt-ipv4: 172.100.100.13
      image: docker-registry.nwl.lab/iol-l2:latest
    graphite:
      kind: linux
      image: netreplica/graphite
      mgmt-ipv4: 172.100.100.100
      env:
        HOST_CONNECTION: ${SSH_CONNECTION}
      binds:
      - __clabDir__/topology-data.json:/htdocs/default/default.json:ro
      - __clabDir__/ansible-inventory.yml:/htdocs/lab/default/ansible-inventory.yml:ro
      ports:
      - 8080:80
      exec:
      - sh -c 'graphite_motd.sh 8080'
      labels:
        graph-hide: 'yes'
  links:
  - endpoints:
    - CE1:Ethernet0/1
    - unmanagedswitch-1:port0
  - endpoints:
    - BR1:Ethernet0/1
    - unmanagedswitch-1:port1
  - endpoints:
    - unmanagedswitch-1:port2
    - CE2:Ethernet0/1
  kinds:
    cisco_iol:
      image: docker-registry.nwl.lab/cisco_iol:17.12.01
