name: bgp-soft-reconfiguration
mgmt:
  network: mgmt-ipv4
  ipv4-subnet: 10.65.97.0/24
topology:
  kinds:
    cisco_iol:
      image: docker-registry.nwl.lab/cisco_iol:17.12.01
  nodes:
    SubZero:
      kind: cisco_iol
      mgmt-ipv4: 10.65.97.100
      startup-config: ./clab-bgp-soft-reconfiguration/SubZero/startup-config.cfg.partial
    Scorpion:
      kind: cisco_iol
      mgmt-ipv4: 10.65.97.110
      startup-config: ./clab-bgp-soft-reconfiguration/Scorpion/startup-config.cfg.partial
  links:
  - endpoints: ['SubZero:Ethernet0/1', 'Scorpion:Ethernet0/1']
